-- Seed Users (Password hashes will be generated by application with BCrypt)
-- Note: These are placeholders - actual password hashes will be generated by MigrationRunner

-- Admin User
INSERT INTO Users (Id, Email, PasswordHash, FirstName, LastName, Role, IsActive, EmailVerified, CreatedAt, UpdatedAt)
SELECT '11111111-1111-1111-1111-111111111111'::UUID,
       'admin@portfolio.com',
       '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5Gy5CrLxQqGHu', -- Admin@123 (placeholder)
       'Admin',
       'User',
       'admin',
       true,
       true,
       NOW() AT TIME ZONE 'UTC',
       NOW() AT TIME ZONE 'UTC'
WHERE NOT EXISTS (SELECT 1 FROM Users WHERE Email = 'admin@portfolio.com');

-- Test User 1
INSERT INTO Users (Id, Email, PasswordHash, FirstName, LastName, Role, IsActive, EmailVerified, CreatedAt, UpdatedAt)
SELECT '22222222-2222-2222-2222-222222222222'::UUID,
       'user1@portfolio.com',
       '$2a$12$8K1p/a0dL1kz8kK8Y8Y8YO8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y', -- User@123 (placeholder)
       'John',
       'Doe',
       'user',
       true,
       true,
       (NOW() AT TIME ZONE 'UTC') - INTERVAL '6 months',
       NOW() AT TIME ZONE 'UTC'
WHERE NOT EXISTS (SELECT 1 FROM Users WHERE Email = 'user1@portfolio.com');

-- Test User 2
INSERT INTO Users (Id, Email, PasswordHash, FirstName, LastName, Role, IsActive, EmailVerified, CreatedAt, UpdatedAt)
SELECT '33333333-3333-3333-3333-333333333333'::UUID,
       'user2@portfolio.com',
       '$2a$12$8K1p/a0dL1kz8kK8Y8Y8YO8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y', -- User@123 (placeholder)
       'Jane',
       'Smith',
       'user',
       true,
       true,
       (NOW() AT TIME ZONE 'UTC') - INTERVAL '4 months',
       NOW() AT TIME ZONE 'UTC'
WHERE NOT EXISTS (SELECT 1 FROM Users WHERE Email = 'user2@portfolio.com');

-- Note: Actual password hashes will be generated by the MigrationRunner service using BCrypt
-- The seed data insertions will be handled by the MigrationRunner after hashing passwords properly
